name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  jsontests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: "rust-blockchain/evm-tests"
        submodules: true
    - name: Submodules
      run: |
        cd evm
        git fetch
        git checkout $GITHUB_SHA
    - name: Run tests
      run: |
        cd jsontests
        cargo test --release --verbose
